export enum Colors {
    TEXT = '#45505E',
    TEXT_MESSAGE ='#8C9CAD',
    TEXT_LABEL_INPUT = '#2E3742',
    BORDER = '#D7E0EB',
    SHADOW = '#EBECED',
    TEXT_VALUE_INPUT = '#8C9CAD',
    BACKGROUND_RADIO_BUTTON = '#008B57'
}