import type { Metadata } from "next";
import { Roboto} from "next/font/google";
import "./globals.css";
import Body from "@/components/body/body";
import NavBar from "@/components/navbar/navbar";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"]
});

export const metadata: Metadata = {
  title: "Stone | Currency",
  description: "Generated by Jessica Aguiar",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-Br" className={roboto.className}>
      <Body>
        <NavBar />
        {children}
      </Body>
    </html>
  );
}
